---
name: Fridgely CD Pipeline

'on':
  push:
    branches: ["master"]

jobs:
  deploy:
    name: Deploy to OCI Server
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        # appleboy/ssh-action v1.0.3
        uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.USERNAME }}/fridgely-project

            git fetch origin master

            NGINX_CHANGED=$(git diff HEAD origin/master -- nginx/nginx.conf | wc -l)

            git reset --hard origin/master
            git clean -fd

            ./gradlew build -x test

            cp build/libs/fridgely.jar fridgely.jar

            docker-compose up -d --no-build --force-recreate app

            if [ "$NGINX_CHANGED" -gt "0" ]; then
              echo "nginx.conf 변경 감지 → nginx 재시작"
              docker-compose restart nginx
            fi